### ISSUE TITLE
For some reason "nats" isn't creating the dynamics libs and installing it as it should

### ISSUE THREAD

**Issue by SolarAquarion** [ekmett/nats#18] opened 2019-08-04 18:11 UTC

**Comment by RyanGlScott** [comment] 2019-08-04 19:19
I'm afraid I don't understand the issue from the title alone. Can you provide a more detailed account of what the bug is, how to reproduce it, and what you would expect to happen instead?

**Comment by SolarAquarion** [comment] 2019-08-04 20:56
@RyanGlScott https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=haskell-nats it should be creating stuff in usr/lib/ghc-8.6.5/site-local, like the compiled nats stuff

**Comment by RyanGlScott** [comment] 2019-08-04 22:55
One thing to keep in mind is that on recent GHCs, `nats` doesn't actually contain any Haskell code, since `Numeric.Natural` was migrated to the `base` library (in other words, `nats` is simply a compatibility package that backports `Numeric.Natural` to old GHCs). If you're not seeing anything in `/usr/lib`, it's because there's deliberately no code to begin with.

**Comment by SolarAquarion** [comment] 2019-08-04 23:22
so i need to patch out nats and fail out of the package that wants it, i
kind of get it once i read through the readme and stuff

**Comment by RyanGlScott** [comment] 2019-08-05 08:21
I'm not sure what exactly you mean in https://github.com/ekmett/nats/issues/18#issuecomment-518044467. There should be no need to patch anything, since depending on `nats` is a no-op on newer versions of GHCs.

**Comment by SolarAquarion** [comment] 2019-08-05 09:40
Thanks, but I mean in a different package

**Comment by RyanGlScott** [comment] 2019-08-05 09:41
OK. In that case, is the issue here resolved? It so, please feel free to close it.

**Comment by SolarAquarion** [comment] 2019-08-05 09:55
Will do

**Closed as completed** 2019-08-05 19:12 UTC
